CONFIG_PATH = vim.fn.stdpath "config"
DATA_PATH = vim.fn.stdpath "data"
CACHE_PATH = vim.fn.stdpath "cache"
TERMINAL = vim.fn.expand "$TERMINAL"
RTP = vim.fn.expand "$RUNTIMEPATH"

O = {
    format_on_save = true,
    auto_close_tree = 0,
    auto_complete = true,
    hidden_files = true,
    wrap_lines = false,
    number = true,
    relative_number = true,
    number_width = 4,
    cmdheight = 2,
    cursorline = true,
    shell = "bash",
    timeoutlen = 100,
    nvim_tree_disable_netrw = 0,
    ignore_case = true,
    smart_case = true,
    lushmode = false,
    hl_search = false,
    document_highlight = false,
    transparent_window = false,
    leader_key = "space",
    vnsip_dir = vim.fn.stdpath "config" .. "/snippets",
}
