#!/bin/sh

# checks for neccesery tools
! command -v ip >>/dev/null  && echo "ip tools are missing." && exit
! command -v nmap>>/dev/null && echo "Nmap is not installed" && exit

ip=$(ip a | grep "inet " | grep -v "127.0.0.1" | awk '{print $2}')
nmap -snV "$ip" | grep "scan report" | sed -e 's/(//g' -e 's/)//g' | awk '{print $6 "\t" $5}' | sed -e 's/^[ \t]*//'
