#!/bin/sh

# make sure virtualbox itself exists
! command -v virtualbox >/dev/null && exit

# Check for the vboxmanage binary
! command -v vboxmanage >/dev/null && exit

# output the list of virtual machines
vm=$(vboxmanage list vms | awk '{print $1}' | cut -d"\"" -f 2 | sort -f | dmenu -i -p "Which machine?")

[ -z "$vm" ] && exit
vboxmanage startvm "$vm"
