#!/bin/sh

command -v pacman >>/dev/null		&& updates=$(pacman -Qu | grep -v "\[ignored\]" | wc -l)
command -v xbps-install >>/dev/null	&& updates=$(xbps-install -Syun | wc -l)

[ "$updates" -gt 0 ] && printf " $updates" || exit 1
