#!/bin/sh
# Updates weather forecast
ping -q -w 1 -c 1 google.com >>/dev/null || exit
#ping -q -w 1 -c 1 "$(ip r | grep default | tail -1 | cut -d ' ' -f 3)" >/dev/null || exit
location="$1"; [ -z "$location" ] || location="$location+"
curl -s "wttr.in/$location" > ~/.local/repo/weatherreport
notify-send "🌞 Weather forecast updated."
