#!/bin/sh

alias 	ka="killall" \
	calcurse="calcurse -D ~/.config/calcurse" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	q="exit" \
	x="sxiv -ft *" \
	ytv="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="youtube-dl -xi --audio-format mp3" \
	l="ls -gGhF --color=auto --group-directories-first" \
	ls="ls -F --color=auto --group-directories-first" \
	la="ls -AF --color=auto --group-directories-first" \
	ll="ls -gGAFh --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	ffmpeg="ffmpeg -hide_banner"

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if possible

vf() { fzf | xargs -r - I % $EDITOR % ;}
