#!/bin/sh

# Colorize commands
alias \
	l="ls -gGhF --color=auto --group-directories-first" \
	ls="ls -F --color=auto --group-directories-first" \
	la="ls -AF --color=auto --group-directories-first" \
	ll="ls -gGAFh --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto"

# Command extensions
alias \
	cp="cp -i" \
	mv="mv -i" \
	rm="rm -I" \
	newsboat="newsboat && refbar news" \
	ffmpeg="ffmpeg -hide_banner"

# Shortcuts
alias \
	ka="killall" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	q="exit" \
	x="sxiv -ft *" \
	ytv="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="youtube-dl -xi -f bestaudio/best --audio-format mp3" \
	..="cd .." \
	dotconf="git --git-dir=$HOME/.local/dotfiles --work-tree=$HOME" \
	vimdiff="nvim -d" \
	fr="manview ."

# Menual config
	tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf"
