#!/bin/sh

alias \
	ka="killall" \
	calcurse="calcurse -D ~/.config/calcurse" \
	tmux="tmux -f ~/.config/tmux/tmux.conf" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	q="exit" \
	x="sxiv -ft *" \
	ytv="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="youtube-dl -xi --audio-format mp3" \
	l="ls -gGhF --color=auto --group-directories-first" \
	ls="ls -F --color=auto --group-directories-first" \
	la="ls -AF --color=auto --group-directories-first" \
	ll="ls -gGAFh --color=auto --group-directories-first" \
	dotconf="git --git-dir=$HOME/.local/dotfiles --work-tree=$HOME" \
	grep="grep --color=auto" \
	vimdiff="nvim -d" \
	ffmpeg="ffmpeg -hide_banner" \
	fr="manview ."
