#!/bin/sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

killall -q bspsubfullscreen; bspsubfullscreen &

killall -q polybar
while pidof polybar >/dev/null; do sleep 1; done

# check for multi monitors
if [ $(bspc query --monitors | wc -l) -gt 1 ]; then
	# Look for the largest monitor and use it as the primary monitor
	monitors=$(xrandr --query | grep -w "connected" | sed -e 's/primary//' | awk '{print $1,$3}')
	mainmonitor=$(echo "$monitors" | sort -k 2 -nr | head -n 1 | awk '{print $1}')
	secondarymonitor=$(bspc query --monitors --names | grep -v "$mainmonitor" | head -n 1)

	bspc monitor $mainmonitor -d 1 2 3 4 5 6
	bspc monitor $secondarymonitor -d 7 8 9 0

	# set polybar on primary and secondary monitors
	MONITOR=$mainmonitor polybar -r top &
	MONITOR=$secondarymonitor polybar -r top &

	MONITOR=$mainmonitor polybar -r bottom &
	MONITOR=$secondarymonitor polybar -r bottom &

else
	bspc monitor -d 1 2 3 4 5 6 7 8 9 0
	setsid polybar -r top &
	setsid polybar -r bottom &
fi

# Start workspaces on the main monitor.
bspc desktop -f 1

bspc config initial_polarity second_child

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config border_width 3
bspc config focused_border_color $(xrdb -query | awk '/color1:/ {print $2}')

bspc config window_gap 5
bspc config top_padding 30
bspc config bottom_padding 30
bspc config left_padding 0
bspc config right_padding 0
bspc config focus_follows_pointer true
bspc config single_monocle false
bspc config gapless_monocle true

pgrep sxhkd | xargs kill 2>/dev/null
sxhkd ~/.config/bspwm/bspwmrc-keys &

bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off

# bspc rule -a firefox desktop='^2'
