#!/bin/sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

# check for multi monitors
if [ $(bspc query --monitors | wc -l) -gt 1 ]; then
	# Look for the largest monitor and use it as the primary monitor
	monitors=$(xrandr --query | grep -w "connected" | sed -e 's/primary//' | awk '{print $1,$3}')
	mainmonitor=$(echo "$monitors" | sort -k 2 -nr | head -n 1 | awk '{print $1}')
	secondarymonitor=$(bspc query --monitors --names | grep -v "$mainmonitor" | head -n 1)

	bspc monitor $mainmonitor -d 1 2 3 4 5 6
	bspc monitor $secondarymonitor -d 7 8 9 0

	# set polybar on primary and secondary monitors
	MONITOR=$mainmonitor polybar -r top &
	MONITOR=$secondarymonitor polybar -r top &

	MONITOR=$mainmonitor polybar -r bottom &
	MONITOR=$secondarymonitor polybar -r bottom &

else
	bspc monitor -d 1 2 3 4 5 6 7 8 9 0
	polybar -r top &
	polybar -r bottom &
fi

# Start workspaces on the main monitor.
bspc desktop -f 1

# If you want a multi-monitor display or something else, I leave that to you to
# arrange. I have this sensible default for most people's use cases.

bspc config border_width 3
bspc config focused_border_color $(xrdb -query | awk '/color7/ {print $2}')
bspc config window_gap 8
bspc config top_padding 30
bspc config focus_follows_pointer true
bspc config single_monocle true
bspc config gapless_monocle true
bspc config top_monocle_padding -5
bspc config bottom_monocle_padding -5

dropdownname="dropdown"
bspc query -N -n .hidden >/dev/null || setsid $TERMINAL -n "$dropdownname" -e dropdown >/dev/null 2>&1 &
bspc rule -a St:$dropdownname hidden=on
bspc rule -a St:$dropdownname sticky=on
bspc rule -a St:$dropdownname state=floating

bspc config external_rules_command "$(which floaters)"

pgrep sxhkd | xargs kill 2>/dev/null
sxhkd ~/.config/bspwm/bspwmrc-keys &

bspc rule -a Zathura state=tiled
# bspc rule -a firefox desktop='^2'
