#!/bin/sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

# check for multi monitors
if [ $(bspc query --monitors | wc -l) -gt 1 ]; then
	# Look for the largest monitor and use it as the primary monitor
	monitors=$(xrandr --query | grep -w "connected" | sed -e 's/primary//' | awk '{print $1,$3}')
	mainmonitor=$(echo "$monitors" | sort -k 2 -nr | head -n 1 | awk '{print $1}')
	secondarymonitor=$(bspc query --monitors --names | grep -v "$mainmonitor" | head -n 1)

	bspc monitor $mainmonitor -d 1 2 3 4 5 6
	bspc monitor $secondarymonitor -d 7 8 9 0

	# set polybar on primary and secondary monitors
	MONITOR=$mainmonitor polybar -r top &
	MONITOR=$secondarymonitor polybar -r top &

else
	bspc monitor -d 1 2 3 4 5 6 7 8 9 10
	polybar -r top &
fi

# Start workspaces on the main monitor.
bspc desktop -f 1

# If you want a multi-monitor display or something else, I leave that to you to
# arrange. I have this sensible default for most people's use cases.

bspc config border_width 4
bspc config focused_border_color $(xrdb -query | awk '/color5/ {print $2}')
bspc config window_gap 15
bspc config top_padding 24	# top_padding I set equal to polybar's height
bspc config focus_follows_pointer true

dropdownname="dropdown"
bspc query -N -n .hidden >/dev/null || setsid $TERMINAL -n "$dropdownname" -e dropdown >/dev/null 2>&1 &
bspc rule -a St:$dropdownname hidden=on
bspc rule -a St:$dropdownname sticky=on
bspc rule -a St:$dropdownname state=floating

bspc config external_rules_command "$(which floaters)"

pgrep sxhkd | xargs kill 2>/dev/null
sxhkd ~/.config/bspwm/bspwmrc-keys &

# bspc rule -a firefox desktop='^2'
