#!/bin/sh

printf "Beginning upgrade.\\n"

command -v xbps-install >>/dev/null && sudo -A xbps-install -yu
command -v yay >>/dev/null			&& yay -Syu

refupdates

printf "\\nUpgrade complete.\\nPress <Enter> to exit window.\\n\\n"
read -r
