#!/bin/sh

# Refresh awesome infobar
awesome-client 'awesome.emit_signal("refbar")'

# Refresh the dwmbar.
# Send SIGTRAP signal to dwmbar script, which will handle it with a trap.
pkill -SIGTRAP dwmbar
