#!/bin/sh

# Refresh awesome infobar
pgrep -x awesome >>/dev/null && awesome-client 'awesome.emit_signal("refbar")'

# Refresh the dwmbar.
# Send SIGTRAP signal to dwmbar script, which will handle it with a trap.
pgrep -x dwm >>/dev/null && pkill -SIGTRAP dwmbar
