#!/bin/sh

case $BLOCK_BUTTON in
	1) lmc audiomixer ;;
	2) lmc mute ;;
	4) lmc up 5 ;;
	5) lmc down 5 ;;
	3) pgrep -x dunst >/dev/null && notify-send "<b>📢 Volume module:</b>
- Shows volume 🔊, 🔇 if muted.
- Middle click to mute.
- Scroll to change."
esac

echo $(amixer get Master | grep -o "[0-9]*%\|\[on\]\|\[off\]" | sed "s/\[on\]/🔊/;s/\[off\]/🔇/")
