#!/usr/bin/env sh

[ "$(pulsemixer --get-mute)" = "1" ] && echo "🔇" && exit

vol=$(pulsemixer --get-volume | awk '{print $1}')

if [ "$vol" -gt "70" ]; then
	icon="🔊"
elif [ "$vol" -lt "30" ]; then
	icon="🔈"
else
	icon="🔉"
fi

echo "$icon $vol%"
