#!/usr/bin/env sh

[ ! -z "$1" ] && BLOCK_BUTTON="$1"

case $BLOCK_BUTTON in
	1) setsid "$TERMINAL" -e dmc control & ;;
	2) dmc toggle & ;;
	4) dmc up & ;;
	5) dmc down & ;;
	3) pidof dunst >/dev/null && notify-send "📢 Volume module" "\- Shows volume 🔊, 🔇 if muted.
- Middle click to mute.
- Scroll to change." ;;
	6) setsid "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

[ "$(dmc state)" = "1" ] && echo "🔇" && exit

vol=$(dmc get)

if [ "$vol" -gt "70" ]; then
	icon="🔊"
elif [ "$vol" -lt "30" ]; then
	icon="🔈"
else
	icon="🔉"
fi

echo "$icon $vol%"
