#!/bin/sh

index=$(mktemp -t bulkmv-index.XXXXXXXXXX)
trap '{ rm -f "${index}" ; }' exit

if [ $# -ne 0 ]; then
    echo "$(echo "$@" | tr ' ' "\n")" > $index
else
	echo "$(ls "$PWD" | tr ' ' "\n")" > $index
fi

index_edit=$(mktemp -t bulkmv-rename.XXXXXXXXXX)
cat $index > $index_edit
$EDITOR $index_edit
if [ $(cat $index | wc -l) -eq $(cat $index_edit | wc -l) ]; then
	max=$(($(cat $index | wc -l)+1))
	counter=1
	while [ $counter -le $max ]; do
		a="$(cat $index | sed "${counter}q;d")"
		b="$(cat $index_edit | sed "${counter}q;d")"
		counter=$(($counter+1))

		[ "$a" = "$b" ] && continue
		[ -e "$b" ] && echo "File exists: $b" && continue
		mv "$a" "$b"
	done
else
	echo "Number of lines must stay the same"
fi
rm $index $index_edit
