#!/usr/bin/env sh

[ -z "$1" ] && echo "Run on ISO!" && exit

device=$(ls /dev/sr* 2>/dev/null | dmenu -i -p "Select Device")
[ -z "$device" ] && exit


burntype=$(printf "CD\\nDVD" | dmenu -i -p "Select Type")
[ -z "$burntype" ] && exit

case "$burntype" in
	"CD" )  command -v cdrecord >/dev/null && cdrecord -v -sao dev="$device" "$1" || echo "error: cdrtools is not installed" ;;
	"DVD" ) command -v growisofs >/dev/null && growisofs -dvd-compat -Z "$device"="$1" || echo "error: dvd+rw-tools is not installed" ;;
	"*" ) echo "option is not recognizd." ;;
esac
