#!/bin/sh

[ ! -z "$1" ] && BLOCK_BUTTON="$1"

case $BLOCK_BUTTON in
	1) pidof dunst >/dev/null && notify-send "This Month" "$(cal --color=always | sed "s/..7m/<b><span color=\"red\">/;s/..27m/<\/span><\/b>/")" && notify-send "Appointments" "$(calcurse -d3)" ;;
	2) $TERMINAL -e calcurse -D ~/.config/calcurse ;;
	3) pidof dunst >/dev/null && notify-send "📅 Time/date module" "\- Left click to show upcoming appointments for the next three days via \`calcurse -d3\` and show the month via \`cal\`
- Middle click opens calcurse if installed" ;;
	6) setsid "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

# date '+%Y %b %d (%a) %I:%M%p' | sed 's/AM/ 🌅/;s/PM/ 🌇/'
t=$(date '+%Y %b %d (%a) %H:%M')

case $(echo "$t" | awk '{print $5}' | cut -d ':' -f1) in
	0[0-5]|2[0-4]) icon="🌃" ;;
	0[5-8]) icon="🌅" ;;
	0[8-9]|1[0-6]) icon="🌄" ;;
	1[6-9]|20) icon="🌇" ;;
	*) icon="⏰" ;;
esac

echo "$t $icon"
