#!/usr/bin/env sh

# This script will compile or run another finishing operation on a document. I
# have this script run via vim.
#
# Compiles .tex. groff (.mom, .ms), .rmd, .md.
# Opens .sent files as sent presentations.
# Runs scripts based on extention or shebang

file=$(readlink -f "$1")
dir=${file%/*}
base="${file%.*}"
ext="${file##*.}"

cd "$dir" || exit

textype() { \
	command="pdflatex"
	( sed 5q "$file" | grep -i -q 'xelatex' ) && command="xelatex"
	$command --output-directory="$dir" "$base" &&
	grep -i addbibresource "$file" >/dev/null &&
	biber --input-directory "$dir" "$base" &&
	$command --output-directory="$dir" "$base" &&
	$command --output-directory="$dir" "$base"
}

case "$ext" in
	ms) refer -PS -e "$file" | groff -me -ms -kejpt -T pdf > "$base".pdf ;;
	mom) refer -PS -e "$file" | groff -mom -kejpt -T pdf > "$base".pdf ;;
	[rR]md) Rscript -e "require(rmarkdown); rmarkdown::render('$file', quiet=TRUE)" ;;
	tex) textype "$file" ;;
	md) if  command -v lowdown >/dev/null; then
			lowdown -d nointem -e super "$file" -Tms | groff -mpdfmark -ms -kept > "$base".pdf
		elif command -v groffdown >/dev/null; then
			groffdown -i "$file" | groff > "$base.pdf"
		else
			pandoc "$file" --pdf-engine=xelatex -o "$base".pdf
		fi ; ;;
	h) sudo -A make install || make ;;
    c) make 2>>/dev/null || cc "$file" -o "$base" && "$base" ;;
    cpp) make 2>>/dev/null || cc "$file" -o "$base" && "$base" ;;
	py) python "$file" ;;
	go) go run "$file" ;;
	sent) setsid sent "$file" 2>/dev/null & ;;
	rs) cargo run "$file" ;;
    *) sed 1q "$file" | grep "^#!/" | sed "s/^#!//" | xargs -r -I % "$file" ;;
esac
