#!/bin/sh

# This script will compile or run another finishing operation on a document. I
# have this script run via vim.
#
# Compiles .tex. groff (.mom, .ms), .rmd, .md.
# Opens .sent files as sent presentations.
# Runs scripts based on extention or shebang

file=$(readlink -f "$1")
dir=${file%/*}
base="${file%.*}"
ext="${file##*.}"

cd "$dir" || exit

textype() { \
  command="pdflatex"
  ( head -n 5 "$file" | grep -qi 'xelatex' ) && command="xelatex"
  $command --output-directory="$dir" "$base" &&
  grep -qi addbibresource "$file" >/dev/null &&
  biber --input-directory "$dir" "$base" &&
  $command --output-directory="$dir" "$base" &&
  $command --output-directory="$dir" "$base"
}

case "$ext" in
  ms) refer -PS -e "$file" | groff -me -ms -kejpt -T pdf > "$base".pdf ;;
  mom) refer -PS -e "$file" | groff -mom -kejpt -T pdf > "$base".pdf ;;
  [rR]md) Rscript -e "require(rmarkdown); rmarkdown::render('$file', quiet=TRUE)" ;;
  tex) textype "$file" ;;
  org) 
    emacs "$file" --batch -u "$USER" -f org-latex-export-to-pdf || \
    pandoc "$file" --pdf-engine=xelatex -o "$base".pdf ;;
  md) 
    if  command -v lowdown >/dev/null; then
      lowdown -d nointem -e super "$file" -Tms | groff -mpdfmark -ms -kept > "$base".pdf
    elif command -v groffdown >/dev/null; then
      groffdown -i "$file" | groff > "$base.pdf"
    else
      pandoc -t ms --highlight-style=kate -s -o "$base".pdf "$file"
  fi ; ;;
  h) sudo -A make install || make ;;
  c) make 2>>/dev/null || cc "$file" -o "$base" && "$base" ;;
  cpp) make 2>>/dev/null || cc "$file" -o "$base" && "$base" ;;
  py) python "$file" ;;
  go) go run "$file" ;;
  sent) setsid sent "$file" 2>/dev/null & ;;
  rs) cargo run "$file" ;;
  *) sed -n '/^#!/s/^#!//p; q' "$file" | xargs -r -I % "$file" ;;
esac
