#!/usr/bin/env sh

[ "$(stat -c %y ~/.local/repo/corona 2>/dev/null | cut -d' ' -f1)" != "$(date '+%Y-%m-%d')" ] && curl -s https://corona-stats.online/Israel > ~/.cache/corona

grep "Israel" ~/.cache/corona |
	sed "s/\s*//g;s/\x1b\[[0-9;]*m//g;s/│/;/g" |
	awk -F';' '{print "😷" $3 " (" $9") 💀" $5 " (" $7 "%)"}'
