#!/bin/sh

trap 'update' 5

delim="|"

status() { \
	infobar
	echo "$delim"
	date '+%Y %b %d (%a) %I:%M%p'
}

update() { \
	xsetroot -name "$(status | tr '\n' ' ')" &
}

while :; do
	update
	sleep 1m &
	wait
done
