#!/usr/bin/env sh

for family in serif sans-serif monospace Arial Helvetica Verdana "Times New Roman" "Courier New" "Cascadia Code" "JetBrains Mono" "Fira Code" ; do
  echo -n "$family: "
  fc-match "$family"
done
