#!/bin/sh

WIDTH="1920"
HEIGHT="1080"

url="https://source.unsplash.com/random/"

if [ -n "$2" ]; then
    WIDTH="$1"
    HEIGHT="$2"
fi

url="${url}${WIDTH}x${HEIGHT}"

mkdir -p "$HOME/Pictures"

file=$(mktemp -u -p "$HOME/Pictures" --suffix=.jpg)

curl -L -s -m 10 --retry 2 "$url" -o "$file" &
