#!/bin/sh

url="https://source.unsplash.com/random/"

if [ -n $1 ] && [ -n $2 ]; then
    url="${url}${1}x${2}"
else
    url="${url}1920x1080"
fi


mkdir -p "$HOME/Pictures"

file=$(mktemp -u -p "$HOME/Pictures" --suffix=.jpg)

curl -L -s -m 10 --retry 2 "$url" -o "$file" &
