#!/usr/bin/env sh

[ ! -z "$1" ] && BLOCK_BUTTON="$1"

case $BLOCK_BUTTON in
	1) notify-send "🖥 CPU hogs" "$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)\\n(100% per core)" ;;
	2) setsid "$TERMINAL" -e htop & ;;
	3) notify-send "🖥 CPU module " "\- Shows CPU temperature.
- Click to show intensive processes.
- Middle click to open htop." ;;
	6) setsid "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

sensors 2>/dev/null | grep -vi 'N/A' | awk '/^temp1/ {print "🌡️ " $2}' | sort -nr | head -n 1 | sed -e "s/C//;s/\.[0-9]//" | grep "."
