#!/usr/bin/env sh

# Set the deliminter character.
delim="|"

status() { \

	# Get current mpd track filename or artist - title if possible.
	music && echo "$delim"

	# Number of available updates
	uppackages && echo "$delim"

	weather && echo "$delim"

	# Print used memory
	memory && echo "$delim"

	# Print cpu heat (only the higher)
	heat && echo "$delim"

	# Get the volume of Pulseaudio mixer volume output.
	audiovol && echo "$delim"

	# Wifi quality percentage and icon.
	network && echo "$delim"

	# Will show all batteries with approximate icon for remaining power.
	battery
}

echo -n "$(status | tr '\n' ' ')"
wait
