#!/usr/bin/env bash
# must use bash for the columns to be ordered...

if command -v rofi >>/dev/null; then
	awk '/^[a-z]/ && last {print $0,"\t",last} {last=""} /^#/{last=$0}' ~/.config/sxhkd/sxhkdrc | column -t -s $'\t' | rofi -p "Keys" -dmenu -i -no-show-icons
elif command -v dmenu >>/dev/null; then
	awk '/^[a-z]/ && last {print $0,"\t",last} {last=""} /^#/{last=$0}' ~/.config/sxhkd/sxhkdrc | column -t -s $'\t' | dmenu -p "Keys" -i -l 30
else
	command -v fzf >>/dev/null && awk '/^[a-z]/ && last {print $0,"\t",last} {last=""} /^#/{last=$0}' ~/.config/sxhkd/sxhkdrc | column -t -s $'\t' | fzf --prompt="Keys" || note "Rofi / dmenu / fzf cannot be found." && exit 1
fi
