#!/usr/bin/env bash
# must use bash for the columns to be ordered...

configfile=$(pidof bspwm >/dev/null && cat ~/.config/sxhkd/sxhkdrc ~/.config/bspwm/bspwmrc-keys || cat ~/.config/sxhkd/sxhkdrc)

if command -v rofi >>/dev/null; then
	echo "$configfile" | awk '/^[a-z]/ && last {print $0,"\t",last} {last=""} /^#/{last=$0}' | column -t -s $'\t' | rofi -p "Keys" -dmenu -i -no-show-icons
elif command -v dmenu >>/dev/null; then
	echo "$configfile" | awk '/^[a-z]/ && last {print $0,"\t",last} {last=""} /^#/{last=$0}' ~/.config/sxhkd/sxhkdrc | column -t -s $'\t' | dmenu -p "Keys" -i -l 30
elif command -v fzf >>/dev/null; then
	echo "$configfile" | awk '/^[a-z]/ && last {print $0,"\t",last} {last=""} /^#/{last=$0}' ~/.config/sxhkd/sxhkdrc | column -t -s $'\t' | fzf --prompt="Keys"
else
	note "Rofi / dmenu / fzf cannot be found."
fi
