#!/usr/bin/env sh

# Pause mpd and send the pause key to all mpv videos:
mpc pause >/dev/null 2>&1
pauseallmpv >/dev/null 2>&1

slock &

# In five seconds, turn off display unless key press in last 4 seconds.
sleep 5 && pidof slock >/dev/null && xset dpms force off
