#!/usr/bin/env sh

man -k "." | \
    awk '{gsub(/\(\w+\)/,"");$2="-"; print $0}' | \
    sort -u -t- -k1,1| \
    fzf -i --bind='Ctrl-p:toggle-preview' --preview-window=up:hidden --preview="echo {} | cut -f 1 -d ' ' | xargs -r man" |\
    awk '{print $1}' | xargs -r man
