#!/usr/bin/env sh

# checks if mpd is installed
! command -v mpd >>/dev/null && echo "mpd is not installed!" && exit 1

# Start daemon if not runing
pidof mpd >>/dev/null || $(mpd && note "Starting mpd daemon...")

command -v ncmpcpp >/dev/null && exec $TERMINAL -e ncmpcpp

# Update media folder
mpc update >>/dev/null
