#!/usr/bin/env sh

[ ! -z "$1" ] && BLOCK_BUTTON="$1"

case $BLOCK_BUTTON in
	1) pidof dunst >/dev/null && notify-send "🧠 Memory hogs" "$(ps axch -o cmd:15,%mem --sort=-%mem | head)" ;;
	3) pidof dunst >/dev/null && notify-send "🧠 Memory module" "\- Shows Memory Used/Total.
- Click to show memory hogs." ;;
esac

# Print used memory
free -h | awk '/Mem/ {print "🧠 " $3 "/" $2}' | sed -e 's/i//g'
