#!/usr/bin/env sh

# Repo list must be specified
[ -z "$1" ] && exit 1

if command -v rofi >>/dev/null ; then
	chosen=$(cut -d ';' -f1 "$1" | rofi -p "Choose" -i -dmenu -no-custom -disable-history | sed "s/ .*//")
elif command -v dmenu >> /dev/null ; then
	chosen=$(cut -d ';' -f1 "$1" | dmenu -i -l 20 -fn Monospace-18 | sed "s/ .*//")
else
		note "Rofi / Dmenu does not exist in path." && exit 1
fi

[ -z "$chosen" ] && exit

if [ -n "$2" ]; then
	xdotool type "$chosen"
else
	echo "$chosen" | tr -d '\n' | xclip -selection clipboard
	notify-send "'$chosen' copied to clipboard." &
fi
