#!/usr/bin/env sh

[ ! -z "$1" ] && BLOCK_BUTTON="$1"

case $BLOCK_BUTTON in
    1) mediaplayer & ;;
    2) mpc toggle ;;
    3) pgrep -x dunst >/dev/null && notify-send "🎵 Music module" "\- Shows mpd song playing.
- Left click opens ncmpcpp.
- Middle click pauses.
- Scroll changes track.";;
    4) mpc prev && refbar music ;;  # scroll up, previous
    5) mpc next && refbar music ;;  # scroll down, next
esac

# Get current mpd track filename or artist - title if possible.
pgrep -x mpd >>/dev/null && mpc -f "[[%artist% - ]%title%]|[%file%]" 2>/dev/null | grep -v "volume:" | head -n 1 | sed -e 's/.mp3//g' | grep '.'
