#!/bin/sh

arch() { \
	case "$1" in
		i*) shift 1 && sudo pacman -S "$@" ;;
		u*) $AUR_BIN -Su --noconfirm || sudo pacman -Su --noconfirm --needed ;;
		r*) shift 1 && sudo pacman -Rns "$@" ;;
		m*) sudo pacman -S ;;
		f*) shift 1 && pacman -Ss "$@" ;;
		l*) pacman -Q ;;
		s*) pacman -Qe ;;
		d*) shift 1 && sudo pacman -Syw "$@" ;;
		g*) sudo pacman -Syuw --noconfirm ;;
		o*) pacman -Qdtq ;;
		c*) sudo pacman -Sc ;;
		p*) $AUR_BIN -Qqu || pacman -Qqu ;;
	esac
}

void() { \
	case "$1" in
		i*) shift 1 && sudo xbps-install "$@" ;;
		u*) sudo xbps-install -Su ;;
		r*) shift 1 && sudo xbps-remove -R "$@" ;;
		m*) sudo xbps-install -S ;;
		f*) shift 1 && xbps-query -Rs "$@" ;;
		l*) xbps-query -l ;;
		s*) xbps-query -m ;;
		d*) shift 1 && sudo xbps-install -D "$@" ;;
        g*) echo "not implemented" ;;
		o*) xbps-query -O ;;
		c*) sudo xbps-remove -O ;;
		p*) sudo xbps-install -un ;;
	esac
}

debi() { \
	case "$1" in
		i*) shift 1; command -v sudo >>/dev/null && sudo apt-get install "$@" || apt-get install "$@" ;;
		u*) command -v sudo >>/dev/null && (sudo apt-get update && sudo apt-get upgrade -y) || (apt-get update && apt-get upgrade) ;;
		r*) shift 1; command -v sudo >>/dev/null && sudo apt-get remove "$@" || apt-get remove "$@" ;;
		m*) command -v sudo >>/dev/null && sudo apt-get update || apt-get update ;;
		f*) shift 1; apt search "$@" ;;
		l*) dpkg --list | awk '{print $2}' ;;
		s*) apt-mark showmanual ;;
        d*) command -v sudo >/dev/null && sudo apt-get install --download-only -y "$@" || apt-get install --download-only -y "$@" ;;
        g*) command -v sudo >/dev/null && (sudo apt-get update && sudo apt-get upgrade --download-only) || (apt-get update && apt-get upgrade --download-only) ;;
		o*) apt autoremove --dry-run 2>/dev/null | grep REMOVED -A 1 | tail -n1 | sed 's/^ \+//g' ;;
		c*) command -v sudo >/dev/null && sudo apt clean || apt clean ;;
		p*) apt-get dist-upgrade -s --quiet=2 | grep ^Inst | sed 's/Inst //g;s/(.*)//g;s/\[\]//g' ;;
	esac
}

if [ -z "$1" ]; then
cat << EOF
pac: cli for generic package manager

Allowd options:
install   Install packages
update    Update system
remove    Remove packages
mirror    Update mirrors
find      Find package in remote repositories
list      List installed packages
show      List explicit installed packages
download  Download only without installation
getall    Download all available updates without installation
orphan    List orphan packages
cache     Clear manager cache
pending   List available updates

EOF
else
	command -v pacman		>>/dev/null && arch "$@" && exit
	command -v xbps-install >>/dev/null && void "$@" && exit
	command -v apt			>>/dev/null && debi "$@" && exit
fi
