#!/usr/bin/env sh

arch() { \
	case "$1" in
		i*) shift 1 && sudo pacman -S "$@" ;;
		u*) yay -Su --noconfirm || sudo pacman -Su --noconfirm ;;
		r*) shift 1 && sudo pacman -Rns "$@" ;;
		m*) sudo pacman -S ;;
		f*) shift 1 && pacman -Ss "$@" ;;
		l*) pacman -Q ;;
		s*) pacman -Qe ;;
		d*) shift 1 && sudo pacman -Syw "$@" ;;
		q*) yay -Qqu || pacman -Qqu ;;
		g*) sudo pacman -Syuw --noconfirm ;;
		o*) pacman -Qdtq ;;
		c*) sudo pacman -Sc ;;
	esac
}

void() { \
	case "$1" in
		i*) shift 1 && sudo xbps-install "$@" ;;
		u*) sudo xbps-install -Su ;;
		r*) shift 1 && sudo xbps-remove -R "$@" ;;
		m*) sudo xbps-install -S ;;
		f*) shift 1 && xbps-query -Rs "$@" ;;
		l*) xbps-query -l ;;
		s*) xbps-query -m ;;
		d*) shift 1 && sudo xbps-install -D "$@" ;;
		q*) sudo xbps-install -un ;;
		o*) xbps-query -O ;;
		c*) sudo xbps-remove -O ;;
	esac
}

debi() { \
	case "$1" in
		i*) shift 1; command -v sudo >>/dev/null && sudo apt install "$@" || apt install "$@" ;;
		u*) command -v sudo >>/dev/null && (sudo apt apdate && sudo apt upgrade) || (apt update && apt upgrade) ;;
		r*) shift 1; command -v sudo >>/dev/null && sudo apt remove "$@" || apt remove "$@" ;;
		m*) command -v sudo >>/dev/null && sudo apt update || apt update ;;
		f*) shift 1; apt search "$@" ;;
		l*) apt list ;;
		s*) apt list | grep "[installed]" ;;
		q*) apt list --upgradable ;;
		o*) command -v sudo >>/dev/null && sudo apt autoremove || apt autoremove;;
	esac
}

if [ -z "$1" ]; then
cat << EOF
pac: cli for generic package manager

Allowd options:
install		Install packages
update		Update system
remove		Remove packages
mirror		Update mirrors
find		Find package in remote repositories
list		List installed packages
show		List explicit installed packages
download	Download only without installation
getall		Download all available updates without installation
query		Query for updated
orphan		List orphan packages
cache		Clear manager cache

EOF
else
	command -v pacman		>>/dev/null && arch "$@" && exit
	command -v xbps-install >>/dev/null && void "$@" && exit
	command -v apt			>>/dev/null && debi "$@" && exit
fi
