#!/bin/sh

prefix=${PASSWORD_STORE_DIR:-$HOME/.password-store}
password_files=$(find "$prefix" -type f -name *.gpg)

password=$(echo "${password_files}" | sed "s|$prefix/||g;s|.gpg||g" \
    | rofi -dmenu -theme dmenu -i -p "Select"  )

[ -z "$password" ] && exit

pass show -c "$password" >/dev/null 2>&1 && \
    notify-send "Password was copied to clipboard"
