#!/usr/bin/env sh

! command -v xclip >/dev/null && note "xclip is not installed" && exit 1
! command -v colorpicker >/dev/null && note "colorpicker is not installed" && exit 1

colorpicker --one-shot --preview --short | xclip -selection clipboard
