#!/bin/sh

# Script arguments
FILE_PATH="${1}"         # Full path of the highlighted file
HEIGHT="${2}"

MIMETYPE="$(file --dereference --brief --mime-type -- "${FILE_PATH}")"

# Settings
HIGHLIGHT_TABWIDTH=2

handle_mime() { \
	case "${MIMETYPE}" in
		text/html) w3m -dump "${FILE_PATH}" ;;
		text/troff) man ./ "${FILE_PATH}" | col -b ;;
		text/*) highlight --replace-tabs="${HIGHLIGHT_TABWIDTH}" -O ansi "${FILE_PATH}" ||\
			bat --style=numbers --color=always "${FILE_PATH}" ||\
			cat "${FILE_PATH}" ;;
		application/zip) atool --list -- "${FILE_PATH}" ;;
		application/*) file --brief "${FILE_PATH}" | tr ',' '\n' ;;
		image/*) chafa --fill=block --symbols=block -c 256 -s 80x"${HEIGHT}" "${FILE_PATH}" ;;
		video/* | audio/*|application/octet-stream) mediainfo "${FILE_PATH}" ;;
		*/pdf) pdftotext -l 10 -nopgbrk -q -- "${FILE_PATH}" - ;;
		*opendocument*) odt2txt "${FILE_PATH}" ;;
	esac
}

case "${FILE_PATH}" in
	*.tar*)	tar tf "${FILE_PATH}" ;;
  *.zip)	unzip -l "${FILE_PATH}" ;;
  *.rar)	unrar l "${FILE_PATH}" ;;
  *.7z)		7z l "${FILE_PATH}" ;;
  *.pdf)	pdftotext "${FILE_PATH}" - ;;
  *)			printf "Type: ${MIMETYPE}\n\n" && handle_mime ;;
esac
