#!/usr/bin/env sh

pidof rofi && echo "rofi is not installed" && exit

# check for rclone
! command -v rclone >>/dev/null && echo "rclone is not installed." && exit


getmount() { \
	[ -z "$chosen" ] && exit 1
	mp="$(find $1 | rofi -dmenu -theme dmenu -i -p "Type in mount point.")"
	[ "$mp" = "" ] && exit 1
	if [ ! -d "$mp" ]; then
		mkdiryn=$(printf "No\\nYes" | rofi -dmenu -theme dmenu -i -p "$mp does not exist. Create it?")
		[ "$mkdiryn" = "Yes" ] && (mkdir -p "$mp" || sudo -A mkdir -p "$mp")
	fi
	}

chosen=$(rclone listremotes | rofi -dmenu -theme dmenu -i -p "Choose remote")
[ -z "$chosen" ] && echo "No remote was chosen." && exit

getmount "/mnt /media /mount /home -maxdepth 5 -type d"
[ -z "$mp" ] && exit

rclone mount "$chosen" "$mp" &
