#!/usr/bin/env sh

case "$1" in
	v*)
		awesome-client 'awesome.emit_signal("refvol")' 2>/dev/null &
		polybar-msg hook volume 1 >/dev/null 2>&1 &
		pkill -RTMIN+10 dwmblocks >/dev/null 2>&1 &
		pkill -RTMIN+10 i3blocks >/dev/null 2>&1 &
		;;
	u*)
		awesome-client 'awesome.emit_signal("refupdates")' 2>/dev/null &
		polybar-msg hook updates 1 >/dev/null 2>&1 &
		pkill -RTMIN+8 dwmblocks >/dev/null 2>&1 &
		pkill -RTMIN+8 i3blocks >/dev/null 2>&1 &
		;;
	m*)
		awesome-client 'awesome.emit_signal("refmusic")' 2>/dev/null &
		polybar-msg hook music 1 >/dev/null 2>&1 &
		pkill -RTMIN+11 dwmblocks >/dev/null 2>&1 &
		pkill -RTMIN+11 i3blocks >/dev/null 2>&1 &
		;;
	w*)
		awesome-client 'awesome.emit_signal("refweather")' 2>/dev/null &
		polybar-msg hook weather 1 >/dev/null 2>&1 &
		pkill -RTMIN+5 dwmblocks >/dev/null 2>&1 &
		pkill -RTMIN+5 i3blocks >/dev/null 2>&1 &
		;;
	k*)
		awesome-client 'awesome.emit_signal("refkeyboard")' 2>/dev/null &
		polybar-msg hook keyboard 1 >/dev/null 2>&1 &
		pkill -RTMIN+3 dwmblocks >/dev/null 2>&1 &
		pkill -RTMIN+3 i3blocks >/dev/null 2>&1 &
		;;
	n*)
		awesome-client 'awesome.emit_signal("refnews")' 2>/dev/null &
		polybar-msg hook news 1 >/dev/null 2>&1 &
		pkill -RTMIN+6 dwmblocks >/dev/null 2>&1 &
		pkill -RTMIN+6 i3blocks >/dev/null 2>&1 &
		;;
    t*)
		awesome-client 'awesome.emit_signal("reftorrent")' 2>/dev/null &
        ;;
esac
