#!/usr/bin/env sh

case "$1" in
	v*)
		awesome-client 'awesome.emit_signal("refvol")' 2>/dev/null &
		polybar-msg hook volume 1 >/dev/null 2>&1 &
		pkill -RTMIN+10 dwmblocks >/dev/null 2>&1 &
		;;
	u*)
		awesome-client 'awesome.emit_signal("refupdates")' 2>/dev/null &
		polybar-msg hook updates 1 >/dev/null 2>&1 &
		pkill -RTMIN+8 dwmblocks >/dev/null 2>&1 &
		;;
	m*)
		awesome-client 'awesome.emit_signal("refmusic")' 2>/dev/null &
		polybar-msg hook music 1 >/dev/null 2>&1 &
		pkill -RTMIN+11 dwmblocks >/dev/null 2>&1 &
		;;
	w*)
		awesome-client 'awesome.emit_signal("refweather")' 2>/dev/null &
		polybar-msg hook weather 1 >/dev/null 2>&1 &
		pkill -RTMIN+5 dwmblocks >/dev/null 2>&1 &
		;;
	*)
		awesome-client 'awesome.emit_signal("refbar")' 2>/dev/null &
		# Send SIGTRAP signal to dwmbar script, which will handle it with a trap.
		pkill -SIGTRAP dwmbar &
		;;
esac
