#!/usr/bin/env sh

! command -v fzf >>/dev/null && echo "fzf is not installed" && exit 127

command -v fd >>/dev/null && \
    ( fd -H -t f -d 1 \..*rc$ ~/ ; \
      fd -H -t f -d 1  \..*profile ~/ ; \
      fd -H -t f . ~/.config/ ~/.local/scripts/ ) \
        | fzf --query="$1" --preview='preview {}' \
              --bind='Ctrl-p:toggle-preview' \
              --preview-window='up:70%:wrap' \
        | xargs -r $EDITOR || \
    find ~/.*profile ~/.*rc ~/.config/ ~/.local/scripts/ -type f \
        | fzf --query="$1" --preview='preview {}' \
              --bind='Ctrl-p:toggle-preview' \
              --preview-window='up:70%:wrap' \
        | xargs -r $EDITOR
