#!/bin/sh

! command -v fzf >>/dev/null && echo "fzf is not installed" && exit 127

FULL="$1"

cmd() { \
    # Using git repo
    if [ -z $FULL ]; then
        root_path="$(dotconf rev-parse --show-toplevel)"
        dotconf ls-files $root_path --full-name | sed "s|^|$root_path/|g"
    else
        SCRIPT_DIR="${HOME}/.local/scripts"
        CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}"

        # Using fd / Using built-in find
        if command -v fd >>/dev/null; then
            fd -H -t f -d 1 \..*rc$ ${HOME}/
            fd -H -t f -d 1 \..*profile ${HOME}/
            fd -H -t f . ${CONFIG_DIR}/ ${SCRIPT_DIR}/
        else
            find \
                ${HOME}/.*profile \
                ${HOME}/.*rc \
                ${CONFIG_DIR}/ \
                ${SCRIPT_DIR}/ \
                -type f
        fi
    fi
}

cmd | fzf --preview='preview {}' \
          --bind='Ctrl-p:toggle-preview' \
          --preview-window='up:70%:wrap' \
    | xargs -r $EDITOR
