#!/usr/bin/env sh

command -v fzf >>/dev/null \
	&& find ~/.*profile ~/.tmux.conf ~/.*rc ~/.config/ ~/.local/scripts/ -type f \
	| fzf --preview='[[ $(file --mime {}) =~ binary ]] &&
	                 echo {} is a binary file ||
					 (bat --style=numbers --color=always {} ||
					 highlight -O ansi -l {} ||
					 coderay {} ||
					 rougify {} ||
					 cat {}) 2> /dev/null | head -500' \
	| xargs -r $EDITOR
