#!/usr/bin/env sh

command -v rg >/dev/null && \
    rg "$1" ~/.local/scripts/ |\
    cut -d':' -f1 |\
    uniq |\
    fzf --preview='preview {}' --bind='Ctrl-p:toggle-preview' \
        --preview-window='up:70%:wrap' |\
    xargs -r $EDITOR || \
grep "$1" ~/.local/scripts/* |\
    cut -d':' -f1 |\
    uniq |\
    fzf --preview='preview {}' --bind='Ctrl-p:toggle-preview' \
        --preview-window='up:70%:wrap' |\
    xargs -r $EDITOR
