#!/usr/bin/env sh

# Display contents of selection via dunst if running.

! pidof dunst >/dev/null && echo "dunst not running." && exit

clip=$(xclip -o -selection clipboard)

prim=$(xclip -o -selection primary)

[ "$clip" != "" ] && notify-send "Clipboard:
$clip"
[ "$prim" != "" ] && notify-send "Primary:
$prim"
