#!/usr/bin/env sh

# If transmission-daemon is running, will ask to kill, else will ask to start.
if pidof transmission-da >/dev/null ;
then
	[ "$(printf "No\\nYes" | rofi -dmenu -theme dmenu -i -p "Kill transmission-daemon?")" = "Yes" ] && killall transmission-da && notify-send -i "$PIX/torrent.svg" "transmission-daemon killed."
else
	ifinstalled transmission-cli || exit
	[ "$(printf "No\\nYes" | rofi -dmenu -theme dmenu -i -p "Start transmission daemon?")" = "Yes" ] && transmission-daemon && notify-send -i "$PIX/torrent.svg" "tranmission-daemon started."
fi
