#!/usr/bin/env sh

ifinstalled transmission-remote-cli transmission-cli || exit

! pidof transmission-da >/dev/null && transmission-daemon && notify-send -i "$PIX/torrent.svg" "Starting torrent daemon..." && sleep 3

$TERMINAL -e transmission-remote-cli
