#!/bin/sh

ifinstalled tremc-git  transmission-cli || exit

! pidof transmission-daemon >/dev/null && \
    transmission-daemon && \
    notify-send "Starting transmission daemon..." && sleep 3

$TERMINAL -e tremc
