#!/usr/bin/env sh

# Get input video files and compress them using ffmpeg

# ffmpeg is required
! command -v ffmpeg /dev/null >>/dev/null && echo "ffmpeg is not installed" && exit 127

green=`tput setaf 2`
blue=`tput setaf 4`
reset=`tput sgr0`

choice=$(command -v fzf >/dev/null && \
	printf "Bad\nLow\nMedium\nGood\nHigh" |
	fzf --prompt "Choose Quality >" || "Good")

case "$choice" in
	"Bad")		quality=30 ;;
	"Low")		quality=28 ;;
	"Medium") quality=25 ;;
	"Good")		quality=23 ;;
	"High")		quality=18 ;;
	*) quality=23;;
esac

for name in "$@"; do
	file=$(readlink -f "$name")
	dir=$(dirname "$file")
	outdir="$dir/compressed"
	filename=$(basename "$file")

	[ ! -d "$outdir" ] && mkdir -p "$outdir"

	echo "${blue}Compressing $file${reset}"
	[ -f "$file" ] && ffmpeg -loglevel error -hide_banner -stats -i "$file" -vcodec libx265 -crf "$quality" -map_metadata 0 -preset veryfast "$outdir/$filename"
	echo "${green}Summerize results:\n$(du -h "$file" "$outdir/$filename")${reset}\n"
done
