#!/usr/bin/env sh

[ ! -z "$1" ] && BLOCK_BUTTON="$1"

weatherreport="${XDG_CACHE_HOME:-$HOME/.cache}/weatherreport"

getforecast() {\
	curl -sf "wttr.in/$LOCATION" > "$weatherreport" &&
	command -v notify-send >/dev/null && notify-send "⛅ Weather" "New weather forecast for today." && refbar weather
}

showweather() {\
	sed '16q;d' "$weatherreport" | grep -wo "[0-9]*%" | sort -rn | sed "s/^/💧 /g;1q" | tr -d '\n' &&
	sed '13q;d' "$weatherreport" | grep -o "m\\(-\\)*[0-9]\\+" | sort -n -t 'm' -k 2n | sed -e 1b -e '$!d' | tr '\n|m' ' ' | awk '{print " 🌙",$1 "°","🌞",$2 "°"}'
}

case $BLOCK_BUTTON in
    1) $TERMINAL -e less -Srf "$weatherreport" ;;
    2) getforecast && showweather ;;
    3) pidof dunst >/dev/null && notify-send "🌈 Weather module" "\- Left click for full forecast.
- Middle click to update forecast.
💧: Chance of rainsnow
🌙: Daily low
🌞: Daily high" ;;
    6) setsid "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

[ "$(stat -c %y "$weatherreport" 2>/dev/null | cut -d' ' -f1)" != "$(date '+%Y-%m-%d')" ]  && getforecast

showweather
