#!/usr/bin/env sh

# Give dmenu list of font-awesome characters to copy.
# Shows the selected character in dunst if running.

# Must have xclip installed to even show menu.
xclip -h >/dev/null 2>&1 || exit

# Check if font list exists
[ ! -f ~/.local/repo/font-awesome-list ] && exit

chosen=$(cat ~/.local/repo/font-awesome-list | awk -F_ '{print $1," ",$2}' | dmenu -i -l 20 -fn Monospace-18)

[ "$chosen" != "" ] || exit

c=$(echo "$chosen" | sed "s/ .*//")
echo "$c" | tr -d '\n' | xclip -selection clipboard
notify-send "'$c' copied to clipboard." &

s=$(echo "$chosen" | sed "s/.*; //" | awk '{print $1}')
echo "$s" | tr -d '\n' | xclip
notify-send "'$s' copied to primary." &
